### ISSUE TITLE
Goal implementeren

### ISSUE THREAD

**Issue by BeeHiveJava** [PTS3-S34A/Soccar#43]
Er moet daadwerkelijk een goal gemaakt kunnen worden.

Wat er moet gebeuren:
- Er moet gedecteerd worden wanneer de bal in welke goal zit.
- De posities van de auto's en de bal moeten gereset worden.
- Er moet een event toegevoegd worden.
- Er moet tekst op het scherm verschijnen.

**Comment by octotentakel** [comment]
Ik zie nu dat ik nog niet bijhoud in welke goal de bal wordt gescoord. Is een kleine aanpassing, dus doe ik morgen.

**Comment by BeeHiveJava** [comment]
Okay, lijkt me goed, dan zal ik deze issue ook open laten.
