### ISSUE TITLE
-

### ISSUE THREAD

**Issue by Isylwin** [PTS3-S34A/Soccar#57]
##

**Comment by BeeHiveJava** [comment]
Thanks for the feedback. Will be fixed.

**Comment by marcgroos** [comment]
Dear,

getMap gets the map.
Thank you for feedback. We hope this resolve your problem.
If you unsatisfied with our support. Please contact support.
Please rate 5 stars for our product.

Thank you

**Comment by Isylwin** [comment]
Hello.

I tried to use your feedback but the instructions were unclear and I got my dick stuck in the ceiling fan.
I reet 1/5.

Bye.
